spring.data.mongodb:
#  uri: mongodb://192.168.1.141,192.168.1.142,192.168.1.143/test?primaryPreferred=true&&w=1&wtimeoutMS=5000
  uri: mongodb://192.168.1.149/test

event-consumer.properties:
  bootstrap.servers: 192.168.1.131:9092
  schema.registry.url: http://192.168.1.137:8081

event-confirmation-consumer.properties:
  bootstrap.servers: 192.168.1.131:9092
  schema.registry.url: http://192.168.1.137:8081

logging:
  level:
    com.example: debug
