event-consumer:
  topic: events-json
  properties:
    spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer

event-confirmation-consumer:
  topic: event_confirmations-json
  properties:
    spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
