event-consumer:
  topic: events-json
  properties:
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.Event
    spring.json.trusted.packages: "com.example"

event-confirmation-consumer:
  topic: event_confirmations-json
  properties:
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.EventConfirmation
    spring.json.trusted.packages: "com.example"
