server.port: 8086

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: info
    com.example: info

spring:
  data:
    mongodb:
#      uri: mongodb://mongo.virtual.box,mongo2.virtual.box,mongo3.virtual.box/test?primaryPreferred=true&&w=majority&wtimeoutMS=5000
      uri: mongodb://mongonode.virtual.box/test

event-consumer:
  topic: events
  send-confirmation: true
  save-event: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-monitor
    group.id: event-monitor-group
    auto.offset.reset: latest
    isolation.level: read_committed
    key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.Event
    spring.json.trusted.packages: com.example.model

event-confirmation-consumer:
  topic: event_confirmations
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-monitor
    group.id: event-monitor-group
    auto.offset.reset: latest
    isolation.level: read_committed
    key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.EventConfirmation
    spring.json.trusted.packages: com.example.model

---
spring.config.activate.on-profile: avro,json-schema

event-consumer:
  properties:
    schema.registry.url: http://confluent.virtual.box:8081
    use.latest.version: true
    schema.reflection: true

event-confirmation-consumer:
  properties:
    schema.registry.url: http://confluent.virtual.box:8081
    use.latest.version: true
    schema.reflection: true

---
spring.config.activate.on-profile: avro

event-consumer:
  topic: events-avro
  properties:
    value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    specific.avro.reader: true

event-confirmation-consumer:
  topic: event_confirmations-avro
  properties:
    value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

---
spring.config.activate.on-profile: json-schema

event-consumer:
  topic: events-json_schema
  properties:
    value.deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer

event-confirmation-consumer:
  topic: event_confirmations-json_schema
  properties:
    value.deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer

---
spring.config.activate.on-profile: tls

server:
  port: 8449
  ssl.key-store: ${KEYSTORE}
  ssl.key-store-type: PKCS12
  ssl.key-store-password: ${KEYSTORE_PASSWORD}
