server.port: 8086

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: INFO
    com.example: DEBUG

spring:
  data:
    mongodb:
      host: mongo.virtual.box
      database: test

event-consumer:
  topic: events
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    group.id: event-monitor-group
    key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.Event
    spring.json.trusted.packages: com.example.model
    enable.auto.commit: false
    isolation.level: read_committed

event-confirmation-consumer:
  topic: event_confirmations
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    group.id: event-confirmation-monitor-group
    key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.EventConfirmation
    spring.json.trusted.packages: com.example.model
    enable.auto.commit: false
    isolation.level: read_committed
