server.port: 8082

kafka:
  producer:
    blocking: true
    properties:
      bootstrap.servers: kafka.virtual.box:9092
      client.id: producer
#      transactional.id: ${HOSTNAME:localhost}
      acks: 1
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: org.springframework.kafka.support.serializer.JsonSerializer

  events-topic: events
