server.port: 8082

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: info
    com.example: info

event-producer:
  topic: events
  blocking: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-producer
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: io.confluent.kafka.streams.serdes.avro.ReflectionAvroSerializer
    schema.registry.url: http://confluent.virtual.box:8081
    auto.register.schemas: true
    latest.compatibility.strict: true
    use.latest.version: true

---
spring.config.activate.on-profile: tls

server:
  port: 8445
  ssl.key-store: ${KEYSTORE}
  ssl.key-store-type: PKCS12
  ssl.key-store-password: ${KEYSTORE_PASSWORD}
