server.port: 8082

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: INFO
    com.example: INFO
    com.example.producer.service.EventDeliveryMonitor: DEBUG

event-producer:
  topic: events
  blocking: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-producer
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
