server.port: 8082

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    com.example: info

event-producer:
  topic: events
  blocking: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-producer
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer

---
spring.config.activate.on-profile: avro,json-schema

event-producer:
  properties:
    schema.registry.url: http://confluent.virtual.box:8081
    auto.register.schemas: true
    use.latest.version: true
    schema.reflection: true

---
spring.config.activate.on-profile: avro

event-producer:
  topic: events-avro
  properties:
    value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

---
spring.config.activate.on-profile: json-schema

event-producer:
  topic: events-json_schema
  properties:
    value.serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer

---
spring.config.activate.on-profile: tls

server:
  port: 8445
  ssl.key-store: ${KEYSTORE}
  ssl.key-store-type: PKCS12
  ssl.key-store-password: ${KEYSTORE_PASSWORD}
