server.port: 8084

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: INFO
    com.example: DEBUG

spring:
  data:
    mongodb:
      host: mongo-single.virtual.box
      database: test

event-consumer:
  topic: events
  send-confirmation: true
  save-event: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-consumer
    group.id: event-consumer-group
    key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.Event
    spring.json.trusted.packages: com.example.model
    isolation.level: read_committed

event-confirmation-producer:
  topic: event_confirmations
  blocking: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-confirmation-producer
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer

---
spring.config.activate.on-profile: tls

server:
  port: 8447
  ssl.key-store: ${KEYSTORE}
  ssl.key-store-type: PKCS12
  ssl.key-store-password: ${KEYSTORE_PASSWORD}
