server.port: 8084

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

logging:
  level:
    root: INFO
    com.example: DEBUG

event-consumer:
  topic: events
  send-confirmation: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-consumer
    group.id: event-consumer-group
    key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    spring.json.value.default.type: com.example.model.Event
    spring.json.trusted.packages: com.example.model

#  spring.kafka.consumer.enable-auto-commit=false
#  spring.kafka.consumer.isolation-level=read_committed

event-confirmation-producer:
  topic: event_confirmations
  blocking: true
  properties:
    bootstrap.servers: kafka.virtual.box:9092
    client.id: event-confirmation-producer
#    transactional.id: ${HOSTNAME:COMPUTERNAME:localhost}
#    acks: 1
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
